### ISSUE TITLE
COACH: autotrack is buggy: auto_pow and autotrack ktx does not work

### ISSUE THREAD

**Issue by tcsabina** [deurk/ktx#76]
The client cannot seems to find the correct player to track when using "auto_pow" or "autotrackktx", so it is in a loop of jumping among players.
"autotrack" seems to work fine.

**Comment by deurk** [comment]
Fixed with 66556c1d61aef08892e2cbc79622e8807ae241e1.

**Comment by tcsabina** [comment]
deurk,
unfortunately it is not yet fixed. I haven't got the time to figure out what is exactly going wrong.
But changeset 66556c1 only fixes #75.
Sorry for the confusion...

toma
